### ISSUE TITLE
Script broken, ZS change?

### ISSUE THREAD

**Issue by DarrenPIngram** [mansuf/zippyshare-downloader#11]
Previously things seemed to work. Am on the latest version. Has ZS changed something, or has something broken locally I've not been aware of?

```
% zippyshare-dl --verbose url.txt
[INFO] Grabbing required informations in https://www61.zippyshare.com/v/op8XYTSL/file.html
[DEBUG] Establishing connection to Zippyshare.
[DEBUG] Successfully established connection to Zippyshare.
[DEBUG] Checking if file is not expired
[DEBUG] Checking if file is exist
[DEBUG] Getting Name file, size, date upload.
[DEBUG] Getting download url.
[DEBUG] pattern1 failed to get download url, ParserError: omg attribute in download button javascript cannot be found
[DEBUG] pattern2 failed to get download url, NameError: The use of 'n' is not allowed. Expression used: n + b + z - 3
[ERROR] all patterns parser failed to get required informations
NoneType: None
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/zippyshare-dl", line 33, in <module>
    sys.exit(load_entry_point('zippyshare-downloader==0.2.0', 'console_scripts', 'zippyshare-dl')())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/zippyshare_downloader/cli/process.py", line 110, in main
    process(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/zippyshare_downloader/cli/process.py", line 39, in process
    files = download(*urls, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/zippyshare_downloader/fetcher.py", line 111, in download
    info = get_info(url)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/zippyshare_downloader/fetcher.py", line 46, in get_info
    return finalization_info(parse_info(url, r.text))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/zippyshare_downloader/parser.py", line 52, in parse_info
    raise ParserError('all patterns parser is failed to get required informations')
zippyshare_downloader.errors.ParserError: all patterns parser is failed to get required information


```
The file url.txt has two URLs.

```
% cat url.txt
https://www61.zippyshare.com/v/op8XYTSL/file.html
https://www70.zippyshare.com/v/Vz9vh7DJ/file.html

```

**Comment by mansuf** [comment]
That's the old version. Update your zippyshare-downloader to v0.2.0 where i add additional patterns (pattern3) for grabbing zippyshare download urls

**Comment by mansuf** [comment]
![image](https://user-images.githubusercontent.com/43638783/147221162-85fdb27c-4c4d-4614-853e-3d3b58c03b29.png)
Your urls works fine, i used v0.2.0 tho. Maybe check your installation ?

**Comment by DarrenPIngram** [comment]
Hmm, I updated with the pip package manager. Sorry if there's a false alarm.

I am not sure, what's the best way to delete the entire installation and reinstall from git?

**Comment by mansuf** [comment]
> I am not sure, what's the best way to delete the entire installation and reinstall from git?
```
pip3 uninstall zippyshare-downloader && pip3 install -U zippyshare-downloader
```
This will reinstall zippyshare-downloader with pip

However, if you still want to uninstall & install from git
```
pip3 uninstall zippyshare-downloader && pip3 install git+https://github.com/mansuf/zippyshare-downloader.git@v0.2.0
```

**Comment by DarrenPIngram** [comment]
Thank you. I used the git version (seems better in case the pip manager has its own source -- that I don't know).

This worked, but I don't know what might have corrupted the previous installation that had worked very well. Anyway, thank you for your assistance and for developing this very useful script/application.

**Comment by mansuf** [comment]
Sure 👍, i will add it in next release. This issue is closed.
