### ISSUE TITLE
Patterns parser issue (i think)

### ISSUE THREAD

**Issue by rcdosado** [mansuf/zippyshare-downloader#14]
using current version, Windows 10, python 3.9. I'm guessing this is zippyshare changing implementations 
> [ERROR] all patterns parser failed to get required informations
NoneType: None
Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\dev\test\env39\Scripts\zippyshare-dl.exe\__main__.py", line 7, in <module>
  File "c:\dev\test\env39\lib\site-packages\zippyshare_downloader\cli\process.py", line 165, in main
    process(**kwargs)
  File "c:\dev\test\env39\lib\site-packages\zippyshare_downloader\cli\process.py", line 80, in process
    file = extract_info(urls, **kwargs)
  File "c:\dev\test\env39\lib\site-packages\zippyshare_downloader\fetcher.py", line 155, in extract_info
    info = get_info(url)
  File "c:\dev\test\env39\lib\site-packages\zippyshare_downloader\fetcher.py", line 51, in get_info
    return finalization_info(parse_info(url, r.text))
  File "c:\dev\test\env39\lib\site-packages\zippyshare_downloader\parser.py", line 53, in parse_info
    raise ParserError('all patterns parser is failed to get required informations')
zippyshare_downloader.errors.ParserError: all patterns parser is failed to get required informations

**Comment by mansuf** [comment]
Fixed in [v0.3.2](https://github.com/mansuf/zippyshare-downloader/releases/tag/v0.3.2)
