### ISSUE TITLE
zippyshare-dl error when upgrade ubuntu...

### ISSUE THREAD

**Issue by kec0a** [mansuf/zippyshare-downloader#22]
**zippyshare-dl** or **zippyshare-downloader** version **0.3.3**, Im using **Python 3.10.6** and **pip 23.0.1** from /usr/local/lib/python3.10/dist-packages/pip (python 3.10)

```
root@ubuntu:~# zippyshare-dl "https://www76.zippyshare.com/v/xxx/file.html" --proxy "socks5h://user:pass@1.2.3.4:1212"
[INFO] Grabbing required informations in https://www76.zippyshare.com/v/xxx/file.html
[INFO] Downloading "ASD.mp4" 
Traceback (most recent call last):
  File "/usr/local/bin/zippyshare-dl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/zippyshare_downloader/cli/process.py", line 165, in main
    process(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/zippyshare_downloader/cli/process.py", line 80, in process
    file = extract_info(urls, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/zippyshare_downloader/fetcher.py", line 158, in extract_info
    file_path = file.download(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/zippyshare_downloader/file.py", line 105, in download
    downloader.download()
  File "/usr/local/lib/python3.10/dist-packages/zippyshare_downloader/downloader.py", line 86, in download
    file_sizes = float(resp.headers.get('Content-Length'))
TypeError: float() argument must be a string or a real number, not 'NoneType'
```

Please help me, thanks **mansuf**!

**Comment by kec0a** [comment]
Im reinstall zippyshare-dl with:

```
python3 -m pip cache purge
python3 -m pip uninstall zippyshare-downloader
python3 -m pip install -U zippyshare-downloader
```

still not fixed.

**Comment by mansuf** [comment]
It was actually pattern change, zippyshare changed their code, i added new pattern in [v0.3.4](https://github.com/mansuf/zippyshare-downloader/releases/tag/v0.3.4). So update your zippyshare-downloader
